function A = g_A(in1,in2)
%G_A
%    A = G_A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Jun-2021 23:20:37

x1 = in1(1,:);
t2 = cos(x1);
t3 = t2.*2.956624792929091e-2;
A = reshape([1.0,0.0,-t3,t3,0.0,1.0,0.0,0.0,1.0./1.0e+3,0.0,1.0,0.0,0.0,1.0./1.0e+3,2.155200121739496e-6,9.999096095057606e-1],[4,4]);
