function B = g_B(in1,in2)
%G_B
%    B = G_B(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Jun-2021 23:20:37

B = reshape([0.0,0.0,1.436800081159664e-2,-1.436800081159664e-2,0.0,0.0,-1.436800081159664e-2,6.026032949292437e-1],[4,2]);
