function next_x = g_f(in1,in2)
%G_F
%    NEXT_X = G_F(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Jun-2021 23:20:37

u1 = in2(1,:);
u2 = in2(2,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = sin(x1);
t3 = u1.*1.436800081159664e-2;
t4 = t2.*2.956624792929091e-2;
next_x = [x1+x3./1.0e+3;x2+x4./1.0e+3;t3-t4-u2.*1.436800081159664e-2+x3+x4.*2.155200121739496e-6;-t3+t4+u2.*6.026032949292437e-1+x4.*9.999096095057606e-1];
