function Quu = g_Quu(in1,in2,in3,R1,in5,u1)
%G_QUU
%    QUU = G_QUU(IN1,IN2,IN3,R1,IN5,U1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    21-Jun-2021 13:27:02

P3_3 = in1(11);
P3_4 = in1(15);
P4_3 = in1(12);
P4_4 = in1(16);
Quu = P3_3.*1.536322366970635e-6-P3_4.*6.443435886103075e-5-P4_3.*6.443435886103075e-5+P4_4.*2.702418900545402e-3+R1.*2.0;
