function H = g_dynamics_H(in1)
%G_DYNAMICS_H
%    H = G_DYNAMICS_H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    26-Jun-2021 00:44:48

H = reshape([7.12991052e-2,1.7e-3,1.7e-3,1.7e-3],[2,2]);
