function c = g_dynamics_c(in1,in2)
%G_DYNAMICS_C
%    C = G_DYNAMICS_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Jun-2021 23:23:58

q1 = in1(1,:);
v2 = in2(2,:);
c = [sin(q1).*2.0577844;v2.*1.5e-4];
