function c = g_dynamics_c(in1,in2)
%G_DYNAMICS_C
%    C = G_DYNAMICS_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    21-Jun-2021 13:26:59

q1 = in1(1,:);
c = [sin(q1).*2.0577844;1.5e-4];
